Add SublimeLinter-contrib-xsim
SublimeLinter/package_control_channel pull request #119
Opened 2022-01-22 18:07 UTC by mzh330521

Verilog/SystemVerilog/VHDL linter based on Xilinx Vivado Simulator

2022-01-26 09:13 UTC, kaste requested changes
Keep the entries sorted, please.

2022-01-27 07:35 UTC, mzh330521 commented
> Keep the entries sorted, please.

Sorry, now I have made the entris sorted.

2022-01-27 10:42 UTC, kaste approved these changes

2022-01-27 10:42 UTC, merged

2022-01-27 10:42 UTC, kaste commented
Cool, let's ship it!